version: "3.5"

networks:
  gitea:
    external: false

services:
  database:
    container_name: PGSQLdb
    image: postgres:15
    volumes:
      - type: bind
        source: ./pgsql
        target: /var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "hear397sew"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_MULTIPLE_DATABASES: "gitea, postfix"
    networks:
      - gitea

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - gitea

  server:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=database:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD="hear397sew"
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - database
