version: "3.5"

services:
  blog:
    container_name: personal-blog
    image: nginx:alpine
    volumes:
      - ./config/hugo/public:/usr/share/nginx/html:ro,z
    restart: always
    ports:
      - 6262:80
