version: "3.5"

services:
  blog:
    container_name: personal-blog
    build:
      context: ./personal-page
      args:
        HUGO_ENV_ARG: "production"
        HUGO_CMD: "-d ${NGINX_HOST}"
    volumes:
        - hugo_data:/var/www/hugo:z

volumes:
  hugo_data:
