version: "3.8"

networks:
  internalnet:
    driver: bridge
    enable_ipv6: false

x-mail: &defaults
  env_file: local.env
  networks:
    - internalnet

services:

  hugo-site:
    <<: *defaults
    container_name: hugo-site
    build: ./config/hugo
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=lieuwe.${NGINX_HOST}
      - VIRTUAL_PORT=6262
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=lieuwe.${NGINX_HOST}
    volumes:
      - ./config/hugo/configure:/etc/nginx/templates/default.conf.template:ro,z
    restart: always
    expose:
      - "6262"
