version: "3.8"

networks:
  internalnet:
    external: false

x-mail: &defaults
  env_file: local.env
  networks:
    - internalnet

services:
  ddnsgd:
    <<: *defaults
    container_name: "ddnsgd"
    image: "ghcr.io/dominickbrasileiro/ddnsgd"
    restart: "always"

  database:
    <<: *defaults
    container_name: pgsqlserver
    image: postgres:15
    volumes:
      - type: bind
        source: ./pgsql
        target: /var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"

  roundcubemail:
    <<: *defaults
    image: roundcube/roundcubemail:latest-fpm
    container_name: roundcube
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    ports:
      - 9000:9000
    volumes:
      - ./mail/html:/var/www/html


  mailserver:
    <<: *defaults
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: zathura.leene.dev
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail/mail-data/:/var/mail/
      - ./mail/mail-state/:/var/mail-state/
      - ./mail/mail-logs/:/var/log/mail/
      - ./mail/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    depends_on:
      - ddnsgd
    restart: always


  adminer:
    <<: *defaults
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
